server:
  port: 8082

spring:
  cloud:
    config:
      server:
        git:
          uri: git@gitee.com:jsenht/ResPrivate.git
          search-paths: springcloudconf
          strict-host-key-checking: false
          ignore-local-ssh-settings: true
          privateKey: |
                    -----BEGIN RSA PRIVATE KEY-----
                    MIIEowIBAAKCAQEAuVa8Q4qx7hKLHWEhg4zguX4GVHxh9cCCaq2sqMhnvGr+o12v
                    eAyFzH735GxQ22dO+wMH+Yx1ufSkEOl+5oKGdj53nQ5+TLnAhwOU/FKES5N7FST/
                    1rP4/a9eiVkEq/yFA/ftaQbpVY94zNUznoO6Jd2gjFCOnmlmU7TgdV7WIjEzbUVw
                    RZJdaF29dNGdE4Vn4qDR/B5vZu/rq59KxGri28Lt1B1OYFgYnPaftaLuh43x2bPQ
                    mZhGUBO8yWgJCInTa+FeLMQRVzhFCHwW+JuOzt4fq7+QkIHxT1U+Da2RXvR8hGIu
                    ZGhZhQRubwU8O5HK3iEMSn7AyLb8HkGYveCtYwIDAQABAoIBAASuKwztmLaxYy/3
                    vvfqe9ZTV2eUyIiDNwfooN6WSQBaF1oayI6YilxyrGHpVlVkE3uFRRNJN8PdaLNA
                    okLB8xFTXIPr1MatPi5qqb2Be/PIoqgTCh7q5pPJdPK0+8g4FUfXX/hyAzx05hEO
                    JUKQgwfnw+EnO6LGeJ4OiEiOf4vXdTOZ+OQ+3xLzobghQ8rr28esyW72otTy5ORa
                    ynUq20ygHMEu0CWcXjbagqDW+mpoNrJ6vQxYQ1uscRAhTt1YYhu2QexOiQT1+WVt
                    CI3LxieVFs5HjYuXjGoeicXK40Lwhwop++ahLqEhUjsppaHcABOcanuPRY8m8csO
                    PuwxsOkCgYEA6ubGVo1uWXyuLIsZUei+KDxZ8yziRbhDVUHFKip4YefXDtPOc26r
                    zRvf5b3hAsEbUlNl1HI/LPAqC6sDf8T/vwZJcM5S3GU49SrQfFCvzgN1s6DUbrGB
                    StHuSFdTxcJuVa7OICkDazjGQDrz26sAkbuhywtpgGpAX4zRroRgWOcCgYEAyfxW
                    f0/r0OcXQSIue7VtlC2w90m7pzG7ncy+UEAHKLWFQfPYeM9A+N6PTfHwwBhVEAbH
                    VE9c24Lm8sU88C521DBTdY6h4aY0KIO7sbrlazMpj5ALfPTz9yGHJop5MAb6efJY
                    fiCfDS+iW+ol+1Ln2v45ohTkggsqhCDSc4PPDCUCgYAwqO2dMF8TmohaIdZ06Um6
                    /AWGIl4dIzaPirhVK8cUQPqDz8yMjPh53LRc2yCpeWc3fp8xixkbLgUHtb1b0mtI
                    Hv1HqPXxQeayotPdbLl+a6kONNrMs2idHy/FPJHV/ZjtlvCMKPLUW0Z2N8AcWSgd
                    CElTzmFkgJ4lLP6isDllMQKBgQCME83A2SJHbBw6dYQbEwV9f/p8ZMwY9WqR0w4h
                    BWZxmwFhbcSwc7sxXNexTJqT/cvwI2NVWvyg1zVnI9ZRE0ghe6pFmrc1kFgXyNQA
                    PAciwwaNo230KMSQnNXnqpzE6/IFZEZuohzrvh8w8z+H/kUBINHDUA3xCeFgZIrO
                    xZhvaQKBgDXddTVzLj0coHECvuWzZ47N1us17q1PdPStPmCTXU79/PFWn6pO/g7s
                    fb6FRZ4KzbCPO+Ocb5Sf0fW7CFfAbtZUmJgg/hrTSWnptt0i9HTWWXmulTjrOqLC
                    G18arQXj+QLMVIuTe/9pTeKO3JDxKzFNzkEPipw4WC40ywzlX0f8
                    -----END RSA PRIVATE KEY-----


